language: generic
os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.2
  
before_install:
  - brew update
  - brew install python
  - virtualenv env -p python
  - source env/bin/activate
  
install:
  - ./install.sh
  - pip install selenium

script:
  - python test.py
